"""create core library tables

Revision ID: 0001_core_library
Revises: 
Create Date: 2026-10-04 04:10:39.894863
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_core_library'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('github_path', sa.String(length=1024), nullable=False),
    sa.Column('book_type', sa.String(length=50), server_default=sa.text("'book'"), nullable=False),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'unknown'"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_books')),
    sa.UniqueConstraint('github_path', name=op.f('uq_books_github_path')),
    sa.UniqueConstraint('slug', name=op.f('uq_books_slug'))
    )
    op.create_table('sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_path', sa.String(length=1024), nullable=False),
    sa.Column('github_sha', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.String(length=20), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("sync_status IN ('pending', 'synced', 'error', 'deactivated')", name=op.f('ck_sync_state_valid_sync_status')),
    sa.CheckConstraint('entity_id > 0', name=op.f('ck_sync_state_positive_entity_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_state')),
    sa.UniqueConstraint('github_path', name=op.f('uq_sync_state_github_path'))
    )
    op.create_index(op.f('ix_sync_state_sync_status'), 'sync_state', ['sync_status'], unique=False)
    op.create_table('volumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('volume_number', sa.Integer(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('github_path', sa.String(length=1024), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_volumes_nonnegative_sort_order')),
    sa.CheckConstraint('volume_number >= 1', name=op.f('ck_volumes_positive_volume_number')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_volumes_book_id_books'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_volumes')),
    sa.UniqueConstraint('book_id', 'slug', name='uq_volumes_book_slug'),
    sa.UniqueConstraint('github_path', name=op.f('uq_volumes_github_path')),
    sa.UniqueConstraint('id', 'book_id', name='uq_volumes_id_book')
    )
    op.create_index(op.f('ix_volumes_book_id'), 'volumes', ['book_id'], unique=False)
    op.create_table('chapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('volume_id', sa.Integer(), nullable=True),
    sa.Column('chapter_number', sa.Integer(), nullable=True),
    sa.Column('chapter_code', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('pov', sa.String(length=255), nullable=True),
    sa.Column('github_path', sa.String(length=1024), nullable=False),
    sa.Column('github_sha', sa.String(length=64), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('paragraph_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chapter_number >= 0', name=op.f('ck_chapters_nonnegative_chapter_number')),
    sa.CheckConstraint('paragraph_count >= 0', name=op.f('ck_chapters_nonnegative_paragraph_count')),
    sa.CheckConstraint('sort_order >= 0', name=op.f('ck_chapters_nonnegative_sort_order')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_chapters_book_id_books'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['volume_id', 'book_id'], ['volumes.id', 'volumes.book_id'], name='fk_chapters_volume_book', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chapters')),
    sa.UniqueConstraint('github_path', name=op.f('uq_chapters_github_path'))
    )
    op.create_index('ix_chapters_book_order', 'chapters', ['book_id', 'is_active', 'sort_order', 'id'], unique=False)
    op.create_index('ix_chapters_volume_order', 'chapters', ['volume_id', 'is_active', 'sort_order', 'id'], unique=False)
    op.create_table('paragraphs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_number', sa.Integer(), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('plain_text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_count >= 0', name=op.f('ck_paragraphs_nonnegative_char_count')),
    sa.CheckConstraint('paragraph_number >= 1', name=op.f('ck_paragraphs_positive_paragraph_number')),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_paragraphs_chapter_id_chapters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paragraphs')),
    sa.UniqueConstraint('chapter_id', 'paragraph_number', name='uq_paragraphs_chapter_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paragraphs')
    op.drop_index('ix_chapters_volume_order', table_name='chapters')
    op.drop_index('ix_chapters_book_order', table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_volumes_book_id'), table_name='volumes')
    op.drop_table('volumes')
    op.drop_index(op.f('ix_sync_state_sync_status'), table_name='sync_state')
    op.drop_table('sync_state')
    op.drop_table('books')
    # ### end Alembic commands ###

