"""preserve source metadata and sync runs

Revision ID: 0002_source_metadata
Revises: 0001_core_library
Create Date: 2026-10-04 04:34:28.404078
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002_source_metadata'
down_revision: Union[str, None] = '0001_core_library'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('github_path', sa.String(length=1024), nullable=False),
    sa.Column('github_sha', sa.String(length=64), nullable=False),
    sa.Column('source_commit', sa.String(length=64), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_documents')),
    sa.UniqueConstraint('github_path', name=op.f('uq_source_documents_github_path'))
    )
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_commit', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sync_runs')
    op.drop_table('source_documents')
    # ### end Alembic commands ###

