"""pin chapter source commits

Revision ID: 0003_chapter_provenance
Revises: 0002_source_metadata
Create Date: 2026-10-04 04:39:45.553672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003_chapter_provenance'
down_revision: Union[str, None] = '0002_source_metadata'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('source_commit', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapters', 'source_commit')
    # ### end Alembic commands ###

