"""index PostgreSQL paragraph full text search

Revision ID: 0004_search_fts
Revises: 0003_chapter_provenance
Create Date: 2026-10-04 04:41:29.600672
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004_search_fts'
down_revision: Union[str, None] = '0003_chapter_provenance'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

