"""register GIN expression index

Revision ID: 0005_fts_index
Revises: 0004_search_fts
Create Date: 2026-10-04 04:42:24.549400
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005_fts_index'
down_revision: Union[str, None] = '0004_search_fts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_paragraphs_search_fts', 'paragraphs', [sa.literal_column("to_tsvector('simple'::regconfig, plain_text)")], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paragraphs_search_fts', table_name='paragraphs', postgresql_using='gin')
    # ### end Alembic commands ###

