"""add terminology and non destructive QA issues

Revision ID: 0006_quality
Revises: 0005_fts_index
Create Date: 2026-10-04 04:47:47.977605
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006_quality'
down_revision: Union[str, None] = '0005_fts_index'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('canonical', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_terms_book_id_books'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terms'))
    )
    op.create_index(op.f('ix_terms_book_id'), 'terms', ['book_id'], unique=False)
    op.create_index('uq_terms_scope_canonical', 'terms', [sa.literal_column('coalesce(book_id, 0)'), 'canonical'], unique=True)
    op.create_table('term_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_term_variants_term_id_terms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_term_variants')),
    sa.UniqueConstraint('term_id', 'variant', name='uq_term_variants_term_variant')
    )
    op.create_table('qa_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source_sha', sa.String(length=64), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('paragraph_number', sa.Integer(), nullable=True),
    sa.Column('detected_value', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_current', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('INFO', 'WARNING', 'ERROR')", name=op.f('ck_qa_issues_valid_severity')),
    sa.CheckConstraint('line_number >= 1', name=op.f('ck_qa_issues_positive_line_number')),
    sa.CheckConstraint('paragraph_number >= 1', name=op.f('ck_qa_issues_positive_paragraph_number')),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_qa_issues_chapter_id_chapters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_issues')),
    sa.UniqueConstraint('chapter_id', 'fingerprint', name='uq_qa_issues_chapter_fingerprint')
    )
    op.create_index(op.f('ix_qa_issues_chapter_id'), 'qa_issues', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_qa_issues_issue_type'), 'qa_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_qa_issues_severity'), 'qa_issues', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_issues_severity'), table_name='qa_issues')
    op.drop_index(op.f('ix_qa_issues_issue_type'), table_name='qa_issues')
    op.drop_index(op.f('ix_qa_issues_chapter_id'), table_name='qa_issues')
    op.drop_table('qa_issues')
    op.drop_table('term_variants')
    op.drop_index('uq_terms_scope_canonical', table_name='terms')
    op.drop_index(op.f('ix_terms_book_id'), table_name='terms')
    op.drop_table('terms')
    # ### end Alembic commands ###

