"""add private reading progress bookmarks and notes

Revision ID: 0007_reading
Revises: 0006_quality
Create Date: 2026-10-04 04:51:41.813912
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0007_reading'
down_revision: Union[str, None] = '0006_quality'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), server_default='local', nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_number', sa.Integer(), nullable=False),
    sa.Column('source_sha', sa.String(length=64), nullable=False),
    sa.Column('completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('paragraph_number >= 1', name=op.f('ck_reading_progress_positive_paragraph_number')),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_reading_progress_book_id_books'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['chapter_id', 'book_id'], ['chapters.id', 'chapters.book_id'], name=op.f('fk_reading_progress_chapter_id_chapters'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reading_progress')),
    sa.UniqueConstraint('user_id', 'chapter_id', name='uq_reading_progress_user_chapter')
    )
    op.create_index(op.f('ix_reading_progress_book_id'), 'reading_progress', ['book_id'], unique=False)
    op.create_index(op.f('ix_reading_progress_chapter_id'), 'reading_progress', ['chapter_id'], unique=False)
    op.create_table('bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), server_default='local', nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.Column('paragraph_number', sa.Integer(), nullable=True),
    sa.Column('source_sha', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('paragraph_number >= 1', name=op.f('ck_bookmarks_positive_paragraph_number')),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.id'], name=op.f('fk_bookmarks_chapter_id_chapters'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraphs.id'], name=op.f('fk_bookmarks_paragraph_id_paragraphs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookmarks'))
    )
    op.create_index(op.f('ix_bookmarks_chapter_id'), 'bookmarks', ['chapter_id'], unique=False)
    op.create_unique_constraint('uq_chapters_id_book', 'chapters', ['id', 'book_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chapters_id_book', 'chapters', type_='unique')
    op.drop_index(op.f('ix_bookmarks_chapter_id'), table_name='bookmarks')
    op.drop_table('bookmarks')
    op.drop_index(op.f('ix_reading_progress_chapter_id'), table_name='reading_progress')
    op.drop_index(op.f('ix_reading_progress_book_id'), table_name='reading_progress')
    op.drop_table('reading_progress')
    # ### end Alembic commands ###

