"""add versioned paragraph embeddings

Revision ID: 0008_embeddings
Revises: 0007_reading
Create Date: 2026-10-04 04:59:34.690212
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0008_embeddings'
down_revision: Union[str, None] = '0007_reading'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('input_characters', sa.Integer(), nullable=False),
    sa.Column('vector_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('dimensions >= 1 AND dimensions <= 3072', name=op.f('ck_embeddings_valid_dimensions')),
    sa.CheckConstraint('input_characters >= 1', name=op.f('ck_embeddings_positive_input_characters')),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraphs.id'], name=op.f('fk_embeddings_paragraph_id_paragraphs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embeddings')),
    sa.UniqueConstraint('paragraph_id', 'provider', 'model', name='uq_embeddings_paragraph_provider_model')
    )
    op.create_index(op.f('ix_embeddings_paragraph_id'), 'embeddings', ['paragraph_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_embeddings_paragraph_id'), table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###

